# action.yml
name: 'retrieve-doppler-secrets'
description: ''
inputs:
  DOPPLER_TOKEN: 
    description: 'doppler token'
    required: true
  VARIABLES:
    required: true
    description: "variables separated with comma"
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.DOPPLER_TOKEN }}
    - ${{ inputs.VARIABLES }}