# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  DOPPLER_TOKEN: 
    description: 'doppler token'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.SECRETS_NAME }}